from django.db import migrations,models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[('auth','0012_alter_user_first_name_max_length')]
    operations=[
        migrations.CreateModel(name='Property',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('reference',models.CharField(blank=True,max_length=40,unique=True)),('title',models.CharField(max_length=180)),('property_type',models.CharField(choices=[('Appartement','Appartement'),('Maison','Maison'),('Studio','Studio'),('Villa','Villa')],max_length=30)),('description',models.TextField(blank=True)),('province',models.CharField(default='Haut-Katanga',max_length=100)),('city',models.CharField(default='Lubumbashi',max_length=100)),('commune',models.CharField(blank=True,max_length=100)),('neighborhood',models.CharField(blank=True,max_length=120)),('bedrooms',models.PositiveIntegerField(default=1)),('salons',models.PositiveIntegerField(default=1)),('bathrooms',models.PositiveIntegerField(default=1)),('parking',models.BooleanField(default=False)),('water',models.BooleanField(default=True)),('electricity',models.BooleanField(default=True)),('security',models.BooleanField(default=True)),('furnished',models.BooleanField(default=False)),('rent',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('deposit',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('margin',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('status',models.CharField(choices=[('draft','Brouillon'),('review','En vérification'),('validated','Validée'),('published','Publiée'),('rented','Louée'),('archived','Archivée'),('rejected','Refusée')],default='draft',max_length=20)),('views',models.PositiveIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('owner',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='properties',to='auth.user'))]),
        migrations.CreateModel(name='Contract',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('reference',models.CharField(blank=True,max_length=40,unique=True)),('role',models.CharField(choices=[('tenant','Locataire'),('owner','Propriétaire')],max_length=20)),('amount',models.DecimalField(decimal_places=2,max_digits=10)),('status',models.CharField(default='active',max_length=20)),('start_date',models.DateField(blank=True,null=True)),('end_date',models.DateField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('property',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='contracts',to='core.property')),('user',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='contracts',to='auth.user'))]),
        migrations.CreateModel(name='Notification',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=180)),('message',models.TextField()),('read',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='notifications',to='auth.user'))]),
        migrations.CreateModel(name='Visit',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('preferred_date',models.DateField(blank=True,null=True)),('preferred_time',models.TimeField(blank=True,null=True)),('status',models.CharField(choices=[('pending','En attente'),('confirmed','Confirmée'),('rejected','Refusée'),('done','Effectuée'),('cancelled','Annulée')],default='pending',max_length=20)),('comment',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('property',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='visits',to='core.property')),('requester',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='visits',to='auth.user'))]),
        migrations.CreateModel(name='Payment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('amount_due',models.DecimalField(decimal_places=2,max_digits=10)),('amount_paid',models.DecimalField(decimal_places=2,default=0,max_digits=10)),('due_date',models.DateField()),('paid_date',models.DateField(blank=True,null=True)),('reference',models.CharField(blank=True,max_length=80)),('status',models.CharField(choices=[('upcoming','À venir'),('paid','Payé'),('partial','Partiellement payé'),('late','En retard'),('cancelled','Annulé')],default='upcoming',max_length=20)),('contract',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='payments',to='core.contract'))]),
    ]
