from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('core','0002_property_rejection_visit_approval')]
    operations=[
        migrations.AddField(model_name='property',name='latitude',field=models.DecimalField(blank=True,decimal_places=6,max_digits=9,null=True)),
        migrations.AddField(model_name='property',name='longitude',field=models.DecimalField(blank=True,decimal_places=6,max_digits=9,null=True)),
        migrations.CreateModel(name='PropertyImage',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('image',models.ImageField(upload_to='properties/%Y/%m/')),('caption',models.CharField(blank=True,max_length=160)),('is_cover',models.BooleanField(default=False)),('order',models.PositiveIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('property',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='images',to='core.property'))],options={'ordering':['order','id']}),
        migrations.CreateModel(name='VisitInspection',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('condition',models.TextField(blank=True)),('meter_readings',models.TextField(blank=True)),('keys_received',models.PositiveIntegerField(default=0)),('notes',models.TextField(blank=True)),('signed_by_tenant',models.BooleanField(default=False)),('signed_by_agent',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('visit',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='inspection',to='core.visit'))]),
        migrations.CreateModel(name='ContractDocument',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('document',models.FileField(upload_to='contracts/%Y/%m/')),('label',models.CharField(default='Document contractuel',max_length=160)),('created_at',models.DateTimeField(auto_now_add=True)),('contract',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='documents',to='core.contract'))]),
        migrations.CreateModel(name='PaymentProof',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('file',models.FileField(upload_to='payments/%Y/%m/')),('note',models.CharField(blank=True,max_length=200)),('created_at',models.DateTimeField(auto_now_add=True)),('payment',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='proofs',to='core.payment')),('uploaded_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='auth.user'))]),
        migrations.CreateModel(name='VerificationDocument',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('kind',models.CharField(choices=[('id_front','Pièce identité — recto'),('id_back','Pièce identité — verso'),('selfie','Selfie de vérification'),('other','Autre')],max_length=20)),('file',models.FileField(upload_to='verification/%Y/%m/')),('status',models.CharField(default='pending',max_length=20)),('note',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='verification_documents',to='auth.user'))]),
        migrations.CreateModel(name='AuditLog',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('action',models.CharField(max_length=120)),('object_type',models.CharField(blank=True,max_length=80)),('object_id',models.CharField(blank=True,max_length=80)),('ip_address',models.GenericIPAddressField(blank=True,null=True)),('details',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='audit_logs',to='auth.user'))],options={'ordering':['-created_at']}),
    ]
