# Generated by Django 4.2.7 on 2026-09-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_signed_rental_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalcase",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "Dossier à préparer"),
                    ("signing", "Contrats et états des lieux à signer"),
                    ("active", "Location active"),
                    ("cancelled", "Dossier annulé"),
                ],
                default="preparing",
                max_length=30,
            ),
        ),
    ]
