# Generated by Django 4.2.7 on 2026-09-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sync_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='postnom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='verificationdossier',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
