from django.core.files.base import ContentFile
from django.db.models.signals import post_save
from django.dispatch import receiver

from .rental_models import RentalDocument
from .rental_contract_generator import generate_contract_pdf


@receiver(post_save, sender=RentalDocument)
def refresh_generated_contract_document(sender, instance, created, **kwargs):
    if instance.document_type not in {'owner_contract', 'tenant_contract'} or not instance.file:
        return
    case = instance.rental_case
    contract_type = 'owner_agreement' if instance.document_type == 'owner_contract' else 'tenant_sublease'
    contract = case.contracts.filter(contract_type=contract_type).first()
    if not contract:
        return
    pdf = generate_contract_pdf(contract)
    filename = f'{contract.reference}.pdf'
    instance.file.save(filename, ContentFile(pdf), save=False)
    # Prevent recursive save: the receiver runs again, but the generated bytes are deterministic.
    # Mark the document as prepared when FASTHOME generated it, preserving uploaded signed files later.
    if instance.status in {'required', 'prepared'}:
        instance.status = 'prepared'
    instance.save(update_fields=['file', 'status', 'updated_at'])
